### PR TITLE
Made Party.ID a GlobalID

### PR DESCRIPTION
**Pull request by danvy**
- GlobalID has explicit operators to ease the upgrade
- Party.ID is now a GlobalID to get scheme support
- New schemes constants like SchemeID_SIRENE
- Readers and writers support for Party.ID as GlobalID with backward compatibility

This PR fixes issue #208

### CODE REVIEW

**Comment by stephanstapel** [comment]
Hi @danvy ,
thanks for the pull request! Do you think the scheme ids should be an enum (don't worry, I could quickly do this).
Second question: does this change need a new major version? Is it breaking?

**Comment by danvy** [comment]
Practically. this could be an enum. We would have to format the output. But as this is a token data type of we could see any character in the future.
I tried to minimize the impact of this modification but it will break some apps. I.E. I had to fix the test project as Assert is not comfortable with conversions.

**Comment by danvy** [comment]
@stephanstapel Do you need something on my part ?

**Comment by stephanstapel** [comment]
no, thanks. I just needed spare time. I have merged the code and cleaned up some stuff.

**Comment by danvy** [comment]
Would it be possible to push an updated nuget package ?

**Comment by stephanstapel** [comment]
done

**Pull request merged**
