### PR TITLE
added support for electronic address for peppol

### PR DESCRIPTION
**Pull request by drocx**
Added support for setting the electronic address for peppol (xrechnung). #216

### CODE REVIEW

**Comment by stephan-nowecor** [comment]
Hi drocx,
thanks for your pull request. Can you please add the functionality to the reader as well and add test cases with both present electronic address and missing electronic address?

**Comment by drocx** [comment]
@stephan-nowecor 
I added tests.

**Comment by stephanstapel** [comment]
Thanks for adding tests. Could you share the link where it is stated that this information is required? I'd like to update the docs accordingly.

**Comment by drocx** [comment]
The fields are only necessary if you want to send the x-rechnung via the Peppol network.
A description of the fields can be found in the following documents:
https://docs.peppol.eu/edelivery/policies/PEPPOL-EDN-Policy-for-use-of-identifiers-4.1.0-2020-03-11.pdf
https://www.ferd-net.de/upload/Dokumente/FACTUR-X_ZUGFeRD_2p0_Teil1_Profil_EN16931_1p03.pdf

In Luxembourg it has been mandatory since this year to process all invoices via Peppol:
https://gouvernement.lu/de/dossiers.gouv_digitalisation%2Bde%2Bdossiers%2B2021%2Bfacturation-electronique.html

Therefore we had to manually upload our x-rechnung with the additional fields with the electronic address here, since we don't have a Peppol address ourselves:
https://guichet.public.lu/de/entreprises/commerce/marches-publics/facturation/emission-facture-electronique-marche-public-contrat-concession.html

As far as I know, in Germany this has so far only been necessary for invoices in the course of a public contract from the federal government:
https://www.e-rechnung-bund.de/ubertragungskanale/peppol/

**Pull request merged**
