### PR TITLE
Made some more fields optional

### PR DESCRIPTION
**Pull request by quotschmacher**

### CODE REVIEW

**Comment by quotschmacher** [comment]
According to validator results

image

**Comment by stephanstapel** [comment]
Please also mind this:

grafik

**Comment by quotschmacher** [comment]
CountrySubsidenty - BT-39 - so this should be CountrySubdivisionName,
AddressLine - BT-162 - so this should be AddressLine3 which is mapped to AdditionalStreetName, which is BT-36. BT-36 is not commented in the Party-Model so I think it should be Street, right?

- AdditionalStreetName - BT-36 - Party.Street
- CountrySubsidenty - BT-39 - Party.CountrySubdivisionName
- AddressLine:Line - BT-162 - Party.AddressLine3

Correct?

**Comment by quotschmacher** [comment]
The description https://portal3.gefeg.com/projectdata/invoice/deliverables/installed/publishingproject/xrechnung%202.1.1%20-%20(ab%2001.02.2022)/xrechnung_ubl_invoice_v2.1.1_01.02.2022.scm/html/de/0272.htm states
AddressLine No

AddressLine No 1 - StreetName (BT-35 / BT-50)
AddressLine No 2 - AdditionalStreetName (BT-36 / BT-51)
AddressLine No 3 - AddressLine:Line (BT-162 / BT-163)

this is what the cii-writer is doing:
```
                writer.WriteOptionalElementString("ram:LineOne", string.IsNullOrWhiteSpace(party.ContactName) ? party.Street : party.ContactName); // buyer: BT-50
                if (!string.IsNullOrWhiteSpace(party.ContactName)) { writer.WriteOptionalElementString("ram:LineTwo", party.Street); } // buyer: BT-51
                writer.WriteOptionalElementString("ram:LineThree", party.AddressLine3); // buyer: BT-163
```

**Pull request merged**
