### PR TITLE
Rework InvoiceType, fix sevral warnings, some work on InvoiceDescript…

### PR DESCRIPTION
**Pull request by SandraEickel**
This should fix at least a part of issue #73 ...

### CODE REVIEW

**Comment by SandraEickel** [comment]
Okay, I don't like the restriction on the Extension classes, but will change them back to internal ...

While fixing the merge conflicts on InvoiceDescriptor.cs (comments only), I've seen that AddCreditorFinancialAccount sets the name property, whereas AddDebitorFinancialAccount does not provide this possibility (even if this is consistent with other places).

I have more breaking changes in my pipe, as I add XML comments to CurrencyCodes and numeric values to CountryCodes and perhaps other enums ...

The current commit (to 2c097c6) does not contain those changes, but a lot of other improvements - hope you didn't work at the same places.

**Comment by SandraEickel** [comment]
I continue working on CurrencyCodes which should fix 100 XML warnings and then on other possible breaking changes to further enums ... keeping old versions of them for an upgrade tool ...

**Comment by SandraEickel** [comment]
Sorry, not completely. InvoiceDescriptor[1|20|21]Writer.cs contain the following code:
```
        private string _translateInvoiceType(InvoiceType type)
        {
            switch (type)
            {
                case InvoiceType.Invoice: return "RECHNUNG";
                case InvoiceType.Correction: return "KORREKTURRECHNUNG";
                case InvoiceType.CreditNote: return "GUTSCHRIFT";
                case InvoiceType.DebitNote: return "";
                case InvoiceType.SelfBilledInvoice: return "";
                default: return "";
            }
        } // !_translateInvoiceType()


        private int _encodeInvoiceType(InvoiceType type)
        {
            if ((int)type > 1000)
            {
                type -= 1000;
            }

            // only these types are allowed
            // 84: 'Wertbelastung/Wertrechnung ohne Warenbezug'
            // 380: 'Handelsrechnung (Rechnung für Waren und Dienstleistungen)'
            // 389: 'Selbst ausgestellte Rechnung (Steuerrechtliche Gutschrift/Gutschriftsverfahren)'
            switch (type)
            {
                case InvoiceType.Correction: return (int)InvoiceType.Invoice;
                case InvoiceType.CreditNote: return (int)InvoiceType.Invoice;
                case InvoiceType.DebitNote: return (int)InvoiceType.Invoice;
                case InvoiceType.Invoice: return (int)InvoiceType.Invoice;
                case InvoiceType.SelfBilledInvoice: return (int)InvoiceType.SelfBilledInvoice;
                default: return (int)InvoiceType.Unknown;
            }
        } // !_translateInvoiceType()        
```
84 is a valid code, but not included in the current enum. The description shows that it is not 384 with the 3 missing, and it's not dealt with. Both Invoices (Rechnungen) and CreditNotes (Gutschriften) are treated as Invoice, the only exception beeing SelfBilledInvoice, everything else becomes unknown. This looked bogus before, but know it's definitivly wrong.

The translate methods spit out German, with more international use of ZUGFeRD-csharp upcoming due to factur-x this should change. Real i18n should happen via seperate files.

I haven't yet dived deep enough into this project to understand the consequences of modifying this code.

With my current commit to 70415c9 I fixed some (XML) comments, now down to 160 times CS1591 ...

Beginning private methods with an underscore violates code styling rules.

**Comment by stephanstapel** [comment]
I'll have a look into invoice type mapping. That's still open in https://github.com/stephanstapel/ZUGFeRD-csharp/issues/80.

Concerning documentation: imho it doesn't make sense to have everything documented. That's at least not my ambition. Documentation where it helps, but clearly not everywhere where the compiler warns. E.g. documenting constructors rarely makes sense.

Concerning the coding style: I agree that public functions should be capitalized, just as you saw in one of my recent commits. Concerning private functions: that's the style I'm using for > 20 years now. I found it to be the best way to clearly mark and identify non-public functions.

**Comment by stephanstapel** [comment]
I double checked the code: the clear text name is not written in case of XRechnung (only Extended). So internationalization probably isn't such a big issue.

I've cleaned the rest up in the last push.

**Pull request merged**
