### PR TITLE
Added LineID, BillingPeriod and Product Characterisitics

### PR DESCRIPTION
**Pull request by patrickthoma**
Added parsing support for line id and billing period (start / end) for trade line items. #147

### CODE REVIEW

**Comment by stephanstapel** [comment]
Thanks for the PR.

A few remarks:
* Great that you implemented this for all versions!
* Could you add this feature to the writers as well?
* Is it possible that you add xml documentation (feel free to copy from the ZUGFeRD standard document) to the new parameters/ properties?
* Could you add a unit test for the new fields (just reading and writing, make sure that default value is null after reading a file without these new properties set)

**Comment by patrickthoma** [comment]
Yes, sure I can do this.

**Comment by patrickthoma** [comment]
I improved the code according to your suggestions, please feel free to review it.

**Comment by stephanstapel** [comment]
Thanks a lot. I already had a first look and will finish the PR probably throughout the weekend.
And I learned something new: I never used TrueForAll before. Cool, thanks!

**Comment by patrickthoma** [comment]
I added read / write functionality as well as unit tests for `<ram:ApplicableProductCharacteristics`. We need to parse this node due to the fact that information relevant for energy consumption invoices (such as meter location and meter numbers) are listed in the product characteristics.

Actually, I wanted to create a new PR for this feature, but unfortunatly it is included in this one. Therefore, I changed the title of this PR.

**Comment by stephanstapel** [comment]
Thanks again for adding this functionality.
It'd be good if you could split the tests into dedicated tests to have more precise test results.

Is it possible that you write some documentation/ how to for ApplicableProductCharacteristics? This would really be helpful for the documentation page of the library. If this is too difficult, some key words and some lines of sample code would also do it.

**Comment by patrickthoma** [comment]
Yes, I can do this. Where exactly should I add documentation and how to?

**Comment by stephanstapel** [comment]
That's great, looking forward to that!
I have created a new section:

grafik

one day I probably need to find a better structure for the documentation though :)

**Pull request merged**
