### PR TITLE
Add support form LegalOrganization

### PR DESCRIPTION
**Pull request by danvy**
Add SpecifiedLegalOrganization of type LegalOrganization to Party as stated by specifications.

### CODE REVIEW

**Review by stephan-nowecor — COMMENTED** [review]
Thanks for the addition.
Could you also add the LegalOrganization as an optional paramter to AddSeller() and modify the test accordingly?

**Comment by danvy** [comment]
> Thanks for the addition. Could you also add the LegalOrganization as an optional paramter to AddSeller() and modify the test accordingly?

Did you meant SetSeller() instead of AddSeller() ?
I also did SetBuyer().

**Comment by danvy** [comment]
Could you update the Nuget package ?

**Comment by stephanstapel** [comment]
done

**Pull request merged**
