### PR TITLE
Adding read support for XRechnung UBL

### PR DESCRIPTION
**Pull request by WhereTheTimeWent**
I've added **read** support for XRechnung in UBL format.

Values that can't be read right now:

- IsTest
- SellerContact.OrgUnit
- SellerContact.FaxNo
- BuyerContact.OrgUnit
- BuyerContact.FaxNo
- Referenced and embedded documents
- ShipFrom
- DeliveryNoteReferencedDocument
- Invoicee
- ServiceCharges
- ReceivableSpecifiedTradeAccountingAccounts
- OrderDate
- SellerOrderReferencedDocument.IssueDateTime
- ContractReferencedDocument.IssueDateTime
- SpecifiedProcuringProject.Name
- TradeLineItem.GlobalID
- TradeLineItem.GrossUnitPrice
- ApplicableProductCharacteristics
- BuyerOrderReferencedDocument
- ContractReferencedDocument
- DeliveryNoteReferencedDocument
- ActualDeliveryDate
- AdditionalReferencedDocuments

I mostly couldn't find the mentioned values - I left _// TODO: Find value_ at those spots (InvoiceDescriptor21UblReader.cs started as a copy of InvoiceDescriptor21Reader.cs).
Referenced and embedded documents won't be read for now.
Still, the most important information can be read with my change.

There's no write support with this change.
I added a simple test.

### CODE REVIEW

**Comment by stephanstapel** [comment]
Wow, thanks for your effort!
Will you be available to maintain this reader? And are you willing to implement the writer as well?

**Comment by WhereTheTimeWent** [comment]
Thank **_you_** for providing this great project! :)

> Will you be available to maintain this reader?

If there are bugs, I will correct them. I can't guarantee that I'll add the missing values I listed above (also, many of them don't seem to exist in UBL).

> And are you willing to implement the writer as well?

I don't plan on adding a writer at the moment, because I don't need it, personally.

**Comment by stephanstapel** [comment]
Do you need all these quantity codes for your use cases? I don't want to add full rec21 since this makes creating new invoices imho a nightmare, having to find the right codes among hundreds. Unfortunately I didn't come across any smart solution so far.

**Comment by WhereTheTimeWent** [comment]
I saw XPP a lot, which wasn't included. I could live without the rest. Gonna push a commit!

**Comment by stephanstapel** [comment]
> I have a question about: BuyerOrderReferencedDocument The OrderNo = BT-13 (order number)
> 
> But where is the date? In which field?

afaik, there is no field for that:

https://docs.peppol.eu/poacc/billing/3.0/syntax/ubl-invoice/cac-OrderReference/

**Comment by BRRIT2017** [comment]
But BT-14 is the order number!
No date

**Comment by BRRIT2017** [comment]
Someone must have thought of something, basically it is needed, but where do you get it from?

**Pull request merged**
