### PR TITLE
remove duplicate/obsolete Methods for compatibility with VB.NET

### PR DESCRIPTION
**Pull request by TomcatBB**

### CODE REVIEW

**Comment by stephanstapel** [comment]
Thanks for the pull request. 
As this pull requests breaks backward compatibility, I would like to include this in version 5.0.
I've got a couple of things I'd like to fix before moving to the new major version, so it might take some days until I pull the request into the master branch.

**Comment by TomcatBB** [comment]
Stephan, i have some more stuff i would like to add, for instance the Preceding Invoice Infos. Is it ok when i merge the changes in this pull request also, or should i add a fresh pull request from a new fork without the breaking changes? Unfortunatly i made the breaking changes direct in my master branch of my fork. I am very new to git so still learning how to best work with it in collaboration.

**Comment by stephanstapel** [comment]
Please split the pull requests!

**Comment by TomcatBB** [comment]
as i see i cant create a new fork as a private user of git, so is there a way to separate the code without the breaking changes? or should i send a new pull request with the new changes, including also the breaking changes, as a second pull request?

**Comment by stephanstapel** [comment]
I guess that's not possible. It'd be always great to split the pull requests per topic, that makes it possible to review, feedback and integrate.

**Comment by TomcatBB** [comment]
i closed this pull request to separate the changes into separate pull requests and branches

**Pull request closed without merging**
