### PR TITLE
Fix SpecifiedLegalOrganization profile

### PR DESCRIPTION
**Pull request by danvy**
SpecifiedLegalOrganization was missing in some profiles

### CODE REVIEW

**Comment by stephanstapel** [comment]
Good morning,

thanks for the pull request. I'm not sure if this is correct either.
From the docs (ZUGFeRD 2.2, i.e. excluding XRechnung specification):

TradingBusinessName:
grafik


SpecifiedLegalOrganization:
grafik

**Comment by danvy** [comment]
In the lastest Factur-X doc, SpecifiedLegalOrganization is introduced in the BASCI WL profile.
I let you decide for XRechnung.
This is a severe issue for us as documents are being rejected.

**Comment by stephan-nowecor** [comment]
ok, thanks. For me to remember later - according to version 1.0.6, SpecifiedLegalOrganization is handled like:

ShipToTradeParty, ShipFromTradeParty, SalesAgentTradeParty, UltimateShipToTradeParty, BuyerTaxRepresentativeTradeParty, ProductEndUserTradeParty, BuyerAgentTradeParty, InvoicerTradeParty, InvoiceeTradeParty, PayerTradeParty:

grafik

SellerTradeParty, BuyerTradeParty, PayeeTradeParty:

grafik

**Comment by stephanstapel** [comment]
ok, thanks. For me to remember later - according to version 1.0.6, SpecifiedLegalOrganization is handled like:

ShipToTradeParty, ShipFromTradeParty, SalesAgentTradeParty, UltimateShipToTradeParty, BuyerTaxRepresentativeTradeParty, ProductEndUserTradeParty, BuyerAgentTradeParty, InvoicerTradeParty, InvoiceeTradeParty, PayerTradeParty:

grafik

SellerTradeParty, BuyerTradeParty, PayeeTradeParty:

grafik

**Comment by stephanstapel** [comment]
TradingBusinessName:

BuyerTradeParty


ShipToTradeParty, SalesAgentTradeParty, BuyerTaxRepresentativeTradeParty, SellerTaxRepresentativeTradeParty, ProductEndUserTradeParty, ...:

grafik

SellerTradeParty, PayeeTradeParty:

grafik

BuyerTradeParty:

grafik


I have no idea why it has been designed like this though...

**Comment by danvy** [comment]
@stephanstapel Are you ok if I add includeLegalOrganization parameter to _writeOptionalParty and set its value on each call accordingly ?

**Comment by stephan-nowecor** [comment]
Imho the change is quite big. As written in my notes above, the necessity to write SpecifiedLegalOrganization differs from party to party. Probably, _WriteOptionalParty() needs to be rewritten to allow this. Do you have ideas for this?

**Comment by stephanstapel** [comment]
Imho the change is quite big. As written in my notes above, the necessity to write SpecifiedLegalOrganization differs from party to party. Probably, _WriteOptionalParty() needs to be rewritten to allow this. Do you have ideas for this?

**Comment by stephanstapel** [comment]
can you please add test cases?

**Comment by stephanstapel** [comment]
@danvy : besides the test cases (added one here: https://github.com/stephanstapel/ZUGFeRD-csharp/blob/695c92de44843d16522ea038c4edd35eb4ee2651/ZUGFeRD-Test/ZUGFeRD21Tests.cs#L210 btw), can you please verify that this modification of your code:

https://github.com/stephanstapel/ZUGFeRD-csharp/commit/695c92de44843d16522ea038c4edd35eb4ee2651

works as expected?

**Comment by danvy** [comment]
Could you push a new release so I can test IRL ?

**Comment by stephanstapel** [comment]
done

**Pull request merged**
